### ISSUE TITLE
React render not resolving the diff in server vs. client graphql response

### ISSUE THREAD

**Issue by jeromecovington** [denvned/isomorphic-relay#16]
Hi, I've got isomorphic-relay working nicely. I am finding however, that while the component renders in the html payload from the server, that when the relay query subsequently runs in the client, it triggers a re-render...effectively removing the server markup from the dom and replacing it with the result from the client, even though they are essentially the same. Do you have any help or pointers on how to avoid this needless resolution of a diff (that should be a "non-diff") in the vdom?

**Comment by thelordoftheboards** [comment]
The message issued by React should show you some of the initial tags of the content found in place, and the content re-generated on the client. What are they?

**Comment by jeromecovington** [comment]
@thelordoftheboards - Which message specifically should I be interested in? I'm not immediately seeing any way to inspect the content found in place vs. generated in the client other than inspecting view-source vs. those seen in the Chrome React debugger.

**Comment by thelordoftheboards** [comment]
What is the message in the console? Can you share it?

**Comment by jeromecovington** [comment]
Ah...well I am seeing this...

```
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) .mrc4mv1mo0.0.0.1"><noscript data-reacti
 (server) .mrc4mv1mo0.0.0.1"><div id="render" data
```

Which is interesting...the query being run on the server and the client is exactly the same, but I do see that the client is using a `noscript` here for templating out the render vs. the server using the `div` as I expect. Interesting...any thoughts on that?

**Comment by thelordoftheboards** [comment]
Unfortunately what is shown does not tell me much.
Are you using any libraries? I used to face a similar problem with earlier versions of Material-UI ...

**Comment by jeromecovington** [comment]
Sorry, what is the relevance of Material UI, here? To me this seems to be a
matter of storing the server side query so that the client does not execute
it again, or allowing all relay queries to maintain the same context.

**Comment by thelordoftheboards** [comment]
Sorry, I did not mean to make it more complex than it needs to be.

In my experience with the Material-UI library, it has been coded in such a way that it would produce different results, whether rendered on the client, or on the server.

**Comment by denvned** [comment]
> To me this seems to be a
> matter of storing the server side query so that the client does not execute
> it again

Yes, that's the point. If the prepared payload returned from server is correctly injected to Relay in the browser, and it covers all the needed data, then Relay does not send any GraphQL queries on page load, and there is no rerender.
