### ISSUE TITLE
Uncaught Invariant Violation: callsFromGraphQL(): Expected a declared value for variable, `$undefined`.

### ISSUE THREAD

**Issue by jeromecovington** [denvned/isomorphic-relay#17]
Here is the code that injects my prepared data for the client:

```
componentWillMount: function () {
  if (isBrowser) {
    var relay = _.get(this.props, 'relay', []);
    console.log(
      'relay',
      relay
    );
    IsomorphicRelay.injectPreparedData(relay);
  }
}
```

Here is the error I am seeing in the browser console.
![image](https://cloud.githubusercontent.com/assets/486493/12954753/e29015aa-cfed-11e5-97b4-632f1d0f5651.png)

Any thoughts as to where this error is coming from?

**Comment by jeromecovington** [comment]
Ah. I was passing `after: null` in my query. Closing.

**Comment by thelordoftheboards** [comment]
I occasionally bump into this, when the returned value is either null, or undefined, or whatever other error my fat fingering has caused. I wonder, is there a good way to quickly find and troubleshoot issues like that?
