### ISSUE TITLE
Object.setPrototypeOf can be changed?

### ISSUE THREAD

**Issue by davide-ganito** [denvned/isomorphic-relay#2]
Hi @denvned and thank you for your work.
I was trying to make isomorphing rendering work on IE9 (sorry is not my fault).
For now the only issue I can see is the Object.setPrototypeOf in `IsomorphicRootContainer`.

There is another way to write it?
Thx!

**Comment by denvned** [comment]
In _isomorphic-relay_, `Object.setPrototypeOf` is polyfilled by _babel-runtime_, ~~so it should not be a problem for IE9.~~ Looks like this polyfill doesn't work in <IE11...
