### ISSUE TITLE
Package affected by Babel 6 inheritance bug.

### ISSUE THREAD

**Issue by fabiosantoscode** [denvned/isomorphic-relay#20]
This package (as well as isomorphic-relay-router) currently doesn't work in IE due to [a very serious inheritance bug](https://phabricator.babeljs.io/T3041) in Babel 6.

The class IsomorphicRenderer doesn't define a default constructor, so one is made for it:

```
        function IsomorphicRenderer() {
            (0, _classCallCheck3.default)(this, IsomorphicRenderer);
            return (0, _possibleConstructorReturn3.default)(this, (0, _getPrototypeOf2.default)(IsomorphicRenderer).apply(this, arguments));
        }
```

The idea of this default constructor is to call the parent class's `constructor`. However, this does not work (because IE<10 lacks `__proto__`?), though.

The current workaround is to vendor the module (as opposed to using npm install) and use babel 5 to compile it.

**Comment by fabiosantoscode** [comment]
I've just verified that dropping in [a new magical getPrototypeOf](https://phabricator.babeljs.io/T3041#67582) gets everything working again.

**Comment by denvned** [comment]
Hi @fabiosantoscode. Thanks for pointing that out. Should be fixed in the latest releases of _isomorphic-relay_ and _isomorphic-relay-router_. Could you verify it works now?

**Comment by fabiosantoscode** [comment]
Hello, I've just verified that this works perfectly using the latest releases.

Thank you!
