### ISSUE TITLE
Example integration with react-router-relay

### ISSUE THREAD

**Issue by hung-phan** [denvned/isomorphic-relay#25]
Do we have any example of integration with [react-router-relay](https://github.com/relay-tools/react-router-relay)? The server rendering part?

**Comment by denvned** [comment]
There is a package that allows using _react-router-relay_ with isomorphic rendering: [isomorphic-relay-router](https://github.com/denvned/isomorphic-relay-router). And it has an example: https://github.com/denvned/isomorphic-relay-router/tree/master/examples/todo.

**Comment by hung-phan** [comment]
Thanks @denvned
