### ISSUE TITLE
support for injection of relayContext in prepareData and shim to RelayEnvironment

### ISSUE THREAD

**Issue by aihornmac** [denvned/isomorphic-relay#28]
Since I have been following the latest progress of react-relay, knowing that `RelayContext` is renamed to `RelayEnvironment` while adding `injectNetworkLayer` and `injectTaskScheduler` methods, it would be so nice if `prepareData` allows a `relayContext` to be passed down, with which I can put authorization into headers for each request on server-side.

btw, this module is so inspiring, thank you so much for you work!

**Comment by denvned** [comment]
Since v0.6 of _isomorphic-relay_, you can create a new instance of a Relay network layer (with injected authentication headers/cookies) on each request and pass it as the second argument to `IsomorphicRelay.prepareData`.
