### ISSUE TITLE
Should offer an isomorphic version of Relay.createContainer

### ISSUE THREAD

**Issue by aihornmac** [denvned/isomorphic-relay#29]
Since now `RelayEnvironment` can be appointed, there grows the need for an `relay` able to `commitUpdate` or do sth else passed in props. I reviewed the source code of react-relay and isomorphic-relay, found that the `relay` passed down to LOC was not the original `relayEnvironment` in context, so I made sth like this

``` js
import React, { Component } from 'react';
import { createContainer, PropTypes as RelayPropTypes } from 'react-relay';

const getDisplayName = (WrappedComponent) => {
  return WrappedComponent.displayName || WrappedComponent.name || 'Component';
};

export default (spec) => (WrappedComponent) => {

  class ComponentWithRelayEnvironment extends Component {

    static displayName = `WithEnv(${getDisplayName(WrappedComponent)})`;

    static contextTypes = {
      relay: RelayPropTypes.Environment
    }

    render () {
      this.props.relay.__proto__ = this.context.relay;
      return <WrappedComponent {...this.props} />;
    }

  }

  return createContainer(ComponentWithRelayEnvironment, spec);
};
```

Hoping this feature could be merged in the next version, good day!

**Comment by denvned** [comment]
After seeing your comment [here](https://github.com/facebook/relay/issues/993#issuecomment-204914923), I think I understand what you want, so I have an answer for you [here](https://github.com/facebook/relay/issues/993#issuecomment-204923470).
