### ISSUE TITLE
Upgrade to Relay 0.8

### ISSUE THREAD

**Issue by thelordoftheboards** [denvned/isomorphic-relay#31]
This is more of a question at this point. Since Relay 0.8 is released:

https://github.com/facebook/relay/releases/tag/v0.8.0

will a new version of isomorphic-relay be required?

**Comment by denvned** [comment]
Sure, I am working on it already.

**Comment by hellatan** [comment]
I couldn't really understand the 0.8.0 relay changelog in regards to isomorphic relay - does the latest changes to relay still require this package? As in isomorphic relay is not native to relay itself? I guess by your latest comment, @denvned, this package still needs to be used with relay?

**Comment by AhmadEl-Banna** [comment]
@denvned Hi any progress on this ?

**Comment by edvinerikson** [comment]
I have created a PR #33  but it needs some more work atm. Feedback/help is very welcome.

**Comment by denvned** [comment]
I've just updated _isomorphic-relay_ to Relay v0.8.0. I'm sorry for delay, I rewrote it almost from scratch to make it less dependant on Relay internals.

**Comment by thelordoftheboards** [comment]
Thank you very much for doing that!

**Comment by thelordoftheboards** [comment]
Is the isomorphic-relay-router in need of upgrade too, or it is good to go as is?

**Comment by juhaelee** [comment]
@denvned Thanks so much man, you're the best! Are you going to update the boilerplate you made as well? 🙏

**Comment by denvned** [comment]
> Is the isomorphic-relay-router in need of upgrade too, or it is good to go as is?

@thelordoftheboards, Now it is updated too.

> Are you going to update the boilerplate you made as well?

@juhaelee, Yes, it is the next item in the plan. :)

**Comment by mattecapu** [comment]
@denvned thank you very much
