### ISSUE TITLE
Allow patch releases for Relay peerDependency

### ISSUE THREAD

**Issue by psalz** [denvned/isomorphic-relay#36]
The Relay peerDependency is currently fixed at `0.8.0`. I get that minor releases usually require changes to this package, but can we get support for patch releases (`~0.8.0`)? It's kind of a pain having to `--force` install `0.8.1`.

**Comment by denvned** [comment]
I have to fix the Relay peerDependency to specific versions because _isomorphic-relay_ still uses some of the internals of Relay which could significantly change even between point releases.
