### ISSUE TITLE
Support for Relay v0.9.0

### ISSUE THREAD

**Issue by thelordoftheboards** [denvned/isomorphic-relay#38]
At this point this is more of a question, as with every other upgrade of Relay. Would you suggest that a new version of isomorphic-relay is necessary, or the current version should be compatible?

**Comment by thelordoftheboards** [comment]
I was able to upgrade my repository https://github.com/codefoundries/UniversalRelayBoilerplate with 0.9. it is using the latest isomorphic-relay and isomorphic-relay-router and all the functionality seems to be working fine. Basic GraphQL queries and mutations work perfectly well. However, I am sure there is a wide variety of possible use cases that are not covered by the boilerplate.

**Comment by denvned** [comment]
Fixed. Excuse me for such delay, it was a pretty intense week for me.
