### ISSUE TITLE
Add Hot Reload Support?

### ISSUE THREAD

**Issue by CoericK** [denvned/isomorphic-relay#39]
It is possible to add Hot Reload Replacement? Maybe we can base on this project? 
https://github.com/Hashnode/mern-starter

**Comment by denvned** [comment]
You can already use it. You can get some ideas from _isomorphic-relay-boilerplate_:
https://github.com/denvned/isomorphic-relay-boilerplate/blob/5dd32f3c5759b9305dc1c731bbf80671824978fc/frontend/webpack-client.config.js#L47
https://github.com/denvned/isomorphic-relay-boilerplate/blob/5dd32f3c5759b9305dc1c731bbf80671824978fc/frontend/src/server/index.js#L15-L16
https://github.com/denvned/isomorphic-relay-boilerplate/blob/5dd32f3c5759b9305dc1c731bbf80671824978fc/frontend/src/app.js#L26-L33
