### ISSUE TITLE
Peer Dependencies

### ISSUE THREAD

**Issue by KCraw** [denvned/isomorphic-relay#44]
Any reason why Relay peer dependency is `0.8.0 || 0.9.0` and not `^0.8.0 || ^0.9.0`? 

I know there used to be a concern with the reliance on Relay internals, but at this point, aren't we safe to rely on minor version?

**Comment by denvned** [comment]
Relay non-public APIs, on which _isomorphic-relay_ depends, might significantly change even in a patch version of Relay, that's why it always references exact versions.

**Comment by thelordoftheboards** [comment]
It seems to work fairly well with 0.9.2, does it make sense to add version like `0.8.0 || 0.9.0 || 0.9.2` or it is not worth the effort since a new version will show up soon anyway?

**Comment by denvned** [comment]
@thelordoftheboards Yes, I forgot to mention I had added 0.9.2.
