### ISSUE TITLE
Is it possible to integrate with react starter kit from http://www.reactstarterkit.com/?

### ISSUE THREAD

**Issue by ariesbrunetyson** [denvned/isomorphic-relay#5]
I'm using react starter kit from (http://www.reactstarterkit.com/) to develop my application. Is this lib compatible with the starter kit? What are all the configuration changes i'm expected to do in order to integrate it to the starter kit?

**Comment by denvned** [comment]
I haven't used _react starter kit_ yet, so, I can't tell. Probably, I will write a starter kit specific to _isomorphic-relay_ later.

Currently, I recommend you to use one of the examples as a starting point:
https://github.com/denvned/isomorphic-relay/tree/master/examples/star-wars
https://github.com/denvned/isomorphic-relay-router/tree/master/examples/todo
