### ISSUE TITLE
Help needed in applying isomorphic-relay

### ISSUE THREAD

**Issue by ghost** [denvned/isomorphic-relay#52]
@denvned, thank you for your awesome work in the field of SSR in Relay :+1: 

I tried to adapt your solution into my open-source project. My project consist of two repos:
- server side: https://github.com/tommyJS/backend-for-react-relay-redux-example
- frontend side: https://github.com/tommyJS/react-relay-redux-example/tree/dev

Unfortunately, when I run the project and hit `localhost:3000`, a page is loading infinitely. I run the project in the following way:
- `npm install`
- `npm run build`
- `npm run start`

... and I don't have any errors. I tried to debug the app, however, with no avail.

If you could check what is wrong and what might the root cause of infinite loading, I would be very grateful. I assume that it is my fault, however, it is quite hard to me to spot it.

**Comment by denvned** [comment]
Can't open the links as the user's account has been deleted.
