### ISSUE TITLE
complex type as argument in queries - fetchWithRetries(): Still no successful response after 1 retries, giving up.

### ISSUE THREAD

**Issue by peet86** [denvned/isomorphic-relay#55]
First and foremost: thank you @denvned for all your hard work with the isomorphic-relay-\* libraries. Reall(a)y amazing stuff! 👍  

I have a small issue now.. I'm trying to make some advanced graphql queries but as soon as I pass an object as argument, I get this error message:

```
Error: fetchWithRetries(): Still no successful response after 1 retries, giving up.
   at [..]/node_modules/fbjs/lib/fetchWithRetries.js:78:25
   at process._tickCallback (node.js:369:9)
```

Example: 

```
countries(limit:3, where:{ active: true }){
   id,
}
```

I tried to pass it as a variable, also tried to escape it and pass it as "escaped string" but nothing helps..
When I'm sending the query directly via Graphiql it works well (so probably nothing wrong with my schema).  As I know Relay also supports this type of conditions so I have a hunch something goes wrong in the isomorphic-relay networklayer..

**Comment by denvned** [comment]
It is unlikely there is a problem in _isomorphic-relay_ in this regard. Maybe reading this can help: https://github.com/facebook/relay/issues/100

**Comment by denvned** [comment]
@peet86, did you try to use the plain Relay without _isomorphic-relay_ to see if it works ok?

**Comment by peet86** [comment]
@denvned sorry for the late answer. yes, it looks like this is a relay lib issue and nothing to do with your library. You can close this.
