### ISSUE TITLE
Use it only for backend?

### ISSUE THREAD

**Issue by martinbavio** [denvned/isomorphic-relay#57]
I got a question for people using this project: would it make sense to only use this for SSR? I got a nice setup already working on the client, so I was wondering if it would make sense to only use the server rendering capabilities of this library. Is it just not worth it and it's better to adapt my client code to also use isomorphic-relay, or it's doable and won't introduce performance pains and/or errors?

Thanks!

**Comment by denvned** [comment]
This library should be used on the both the server and the client to make it work.
