### ISSUE TITLE
Upgrade to relay modern

### ISSUE THREAD

**Issue by hung-phan** [denvned/isomorphic-relay#67]
Hi @denvned,

do you have any plan to upgrade the version of react-relay to 1.0.0?

**Comment by robrichard** [comment]
@hung-phan I have a PR to support classic mode in react-relay@1.0.0 https://github.com/denvned/isomorphic-relay/pull/66

For relay modern, I have an example of how to do isomorphic rendering without `isomorphic-relay`: https://github.com/robrichard/relay-modern-isomorphic-example
