### ISSUE TITLE
Can this somehow be used with react-rails

### ISSUE THREAD

**Issue by shaimo** [denvned/isomorphic-relay#8]
I have an isomorphic application using react-router and react-rails and it works fine (both server and client). Now I'm starting to use Relay and obviously I cannot render it on the server (it uses timeout, etc). I don't use anywhere preparedata or match so not sure how to apply this or isomorphic-relay-router...
Thanks

**Comment by denvned** [comment]
Does Relay works fine for you on the client? Do plan to use [react-router-relay](https://github.com/relay-tools/react-router-relay)? - It is a bit tricky to use Relay with bare react-router.

**Comment by shaimo** [comment]
@denvned yes, I managed to get it to work on the client (and even with react-rails), and yes - using react-router-relay. But it doesn't work when trying to render on the server (prerender option of react-rails). It sounds like isomorphic-relay or isomorphic-relay-router could help but I guess I will first need to get rid of react-rails and somehow do the rendering myself, which I'm trying to avoid...

**Comment by denvned** [comment]
I never used react-rails, so unfortunately I can't help you with this.
